import Head from 'next/head'
import Input from '../components/Banner/Input'
import Brand from '../components/Brand/Brand'
import Finnbox from '../components/FinnBox/Finnbox'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import CopyRight from './../components/CopyRight/CopyRight';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import Card from './../components/Card/Card';
export default function Home({ data }) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Input />
      <Brand />
      <Finnbox />
      <div className="container">
        <div className="row">
          {
            data.map(card => < Card key={card.img} cardData={card} />)
          }
        </div>
      </div>
      <Footer />
      <CopyRight />

    </div>
  )
};


export async function getStaticProps() {
  const res = await fetch('https://jsonkeeper.com/b/5YV6')
  const data = await res.json();

  return {
    props: {
      data
    }
  }
}




